// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaULLcIWPNCj4e5G8IuUxAf0V82voXBZc',
    appId: '1:641270616501:web:53b9be36c0596810d549fc',
    messagingSenderId: '641270616501',
    projectId: 'flash-chat-7c118',
    authDomain: 'flash-chat-7c118.firebaseapp.com',
    storageBucket: 'flash-chat-7c118.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAax-sJr_P8jRfrqYLAKch85yIzeu8cGes',
    appId: '1:641270616501:android:9f30ce8bd205ef4dd549fc',
    messagingSenderId: '641270616501',
    projectId: 'flash-chat-7c118',
    storageBucket: 'flash-chat-7c118.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyFvmrKCAETIqDvUchc1N9FLlFDV5eoBA',
    appId: '1:641270616501:ios:492db1eab6473172d549fc',
    messagingSenderId: '641270616501',
    projectId: 'flash-chat-7c118',
    storageBucket: 'flash-chat-7c118.appspot.com',
    iosClientId: '641270616501-q5fj52i22u825gr36i3jlnbauks3u9gd.apps.googleusercontent.com',
    iosBundleId: 'com.mayur.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyFvmrKCAETIqDvUchc1N9FLlFDV5eoBA',
    appId: '1:641270616501:ios:492db1eab6473172d549fc',
    messagingSenderId: '641270616501',
    projectId: 'flash-chat-7c118',
    storageBucket: 'flash-chat-7c118.appspot.com',
    iosClientId: '641270616501-q5fj52i22u825gr36i3jlnbauks3u9gd.apps.googleusercontent.com',
    iosBundleId: 'com.mayur.flashChat',
  );
}
